//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Проект
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class demo_studentEntities : DbContext
    {
        public demo_studentEntities()
            : base("name=demo_studentEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<class_tab> class_tab { get; set; }
        public virtual DbSet<grade> grade { get; set; }
        public virtual DbSet<logins> logins { get; set; }
        public virtual DbSet<members> members { get; set; }
        public virtual DbSet<person> person { get; set; }
        public virtual DbSet<pol_tab> pol_tab { get; set; }
        public virtual DbSet<prepod> prepod { get; set; }
        public virtual DbSet<studnow_tab> studnow_tab { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<zavuch> zavuch { get; set; }
    }
}
